### ISSUE TITLE
Prevents beaming creatures down in Space Stage

### ISSUE THREAD

**Issue by Traehgniw** [Studumb/RemoveGlideCap#1]
Hello! I had this mod, and could not beam creatures down to a planet to fill out the ecology in Space Stage. They just remained floating at the level of the ship and could not be retrieved either.

When I removed the mod, creatures descended properly in the beam and could be placed to fill out the ecology.

Interestingly, it happened with a species that did not have wings, so it wasn't just flying in place.

**Comment by Studumb** [comment]
Thank you for reporting the bug, I will review the code and fix the issue

**Comment by Studumb** [comment]
> Hello! I had this mod, and could not beam creatures down to a planet to fill out the ecology in Space Stage. They just remained floating at the level of the ship and could not be retrieved either.
> 
> When I removed the mod, creatures descended properly in the beam and could be placed to fill out the ecology.
> 
> Interestingly, it happened with a species that did not have wings, so it wasn't just flying in place.

But are you able to reproduce the bug with the mod installed?
